# Import libraries

In [1]:
# load libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Load Dataset

- Dataset taken from: https://www.kaggle.com/code/faressayah/decision-trees-random-forest-for-beginners

In [2]:
dataset = pd.read_csv('HR-Employee-Attrition.csv')

In [3]:
dataset

Age Attrition     BusinessTravel  DailyRate              Department  \
0      41       Yes      Travel_Rarely       1102                   Sales   
1      49        No  Travel_Frequently        279  Research & Development   
2      37       Yes      Travel_Rarely       1373  Research & Development   
3      33        No  Travel_Frequently       1392  Research & Development   
4      27        No      Travel_Rarely        591  Research & Development   
...   ...       ...                ...        ...                     ...   
1465   36        No  Travel_Frequently        884  Research & Development   
1466   39        No      Travel_Rarely        613  Research & Development   
1467   27        No      Travel_Rarely        155  Research & Development   
1468   49        No  Travel_Frequently       1023                   Sales   
1469   34        No      Travel_Rarely        628  Research & Development   

      DistanceFromHome  Education EducationField  EmployeeCount  \
0                    1          2  Life Sciences              1   
1                    8          1  Life Sciences              1   
2                    2          2          Other              1   
3                    3          4  Life Sciences              1   
4                    2          1        Medical              1   
...                ...        ...            ...            ...   
1465                23          2        Medical              1   
1466                 6          1        Medical              1   
1467                 4          3  Life Sciences              1   
1468                 2          3        Medical              1   
1469                 8          3        Medical              1   

      EmployeeNumber  ...  RelationshipSatisfaction StandardHours  \
0                  1  ...                         1            80   
1                  2  ...                         4            80   
2                  4  ...                         2            80   
3                  5  ...                         3            80   
4                  7  ...                         4            80   
...              ...  ...                       ...           ...   
1465            2061  ...                         3            80   
1466            2062  ...                         1            80   
1467            2064  ...                         2            80   
1468            2065  ...                         4            80   
1469            2068  ...                         1            80   

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                    0                  8                      0   
1                    1                 10                      3   
2                    0                  7                      3   
3                    0                  8                      3   
4                    1                  6                      3   
...                ...                ...                    ...   
1465                 1                 17                      3   
1466                 1                  9                      5   
1467                 1                  6                      0   
1468                 0                 17                      3   
1469                 0                  6                      3   

     WorkLifeBalance  YearsAtCompany YearsInCurrentRole  \
0                  1               6                  4   
1                  3              10                  7   
2                  3               0                  0   
3                  3               8                  7   
4                  3               2                  2   
...              ...             ...                ...   
1465               3               5                  2   
1466               3               7                  7   
1467               3               6                  2   
1468               2               9    

# Get Matrix of Features & Dependent Variable Vector

In [4]:
# Observe that though these might have meaningful info, they still have the same value for each record
# so, they are unnecessary columns
print((dataset['Over18'] == 'Y').all())
print((dataset['StandardHours'] == 80).all())

True
True


In [5]:
# drop unnecessary columns
dataset.drop(['EmployeeCount', 'EmployeeNumber', 'Over18', 'StandardHours'], axis = 'columns', inplace = True)

In [6]:
dataset

Age Attrition     BusinessTravel  DailyRate              Department  \
0      41       Yes      Travel_Rarely       1102                   Sales   
1      49        No  Travel_Frequently        279  Research & Development   
2      37       Yes      Travel_Rarely       1373  Research & Development   
3      33        No  Travel_Frequently       1392  Research & Development   
4      27        No      Travel_Rarely        591  Research & Development   
...   ...       ...                ...        ...                     ...   
1465   36        No  Travel_Frequently        884  Research & Development   
1466   39        No      Travel_Rarely        613  Research & Development   
1467   27        No      Travel_Rarely        155  Research & Development   
1468   49        No  Travel_Frequently       1023                   Sales   
1469   34        No      Travel_Rarely        628  Research & Development   

      DistanceFromHome  Education EducationField  EnvironmentSatisfaction  \
0                    1          2  Life Sciences                        2   
1                    8          1  Life Sciences                        3   
2                    2          2          Other                        4   
3                    3          4  Life Sciences                        4   
4                    2          1        Medical                        1   
...                ...        ...            ...                      ...   
1465                23          2        Medical                        3   
1466                 6          1        Medical                        4   
1467                 4          3  Life Sciences                        2   
1468                 2          3        Medical                        4   
1469                 8          3        Medical                        2   

      Gender  ...  PerformanceRating  RelationshipSatisfaction  \
0     Female  ...                  3                         1   
1       Male  ...                  4                         4   
2       Male  ...                  3                         2   
3     Female  ...                  3                         3   
4       Male  ...                  3                         4   
...      ...  ...                ...                       ...   
1465    Male  ...                  3                         3   
1466    Male  ...                  3                         1   
1467    Male  ...                  4                         2   
1468    Male  ...                  3                         4   
1469    Male  ...                  3                         1   

      StockOptionLevel TotalWorkingYears  TrainingTimesLastYear  \
0                    0                 8                      0   
1                    1                10                      3   
2                    0                 7                      3   
3                    0                 8                      3   
4                    1                 6                      3   
...                ...               ...                    ...   
1465                 1                17                      3   
1466                 1                 9                      5   
1467                 1                 6                      0   
1468                 0                17                      3   
1469                 0                 6                      3   

     WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
0                  1               6                   4   
1                  3              10                   7   
2                  3               0                   0   
3                  3               8                   7   
4                  3               2                   2   
...              ...             ...                 ...   
1465               3               5                   2   
1466               3               7                   7   
1467              

In [7]:
# get matrix of features and dependent variable vector 
x = dataset.drop(['Attrition'], axis = 'columns') # this is are dataframe, later it them into numpy ndarray
y = dataset['Attrition'].values

In [8]:
x

Age     BusinessTravel  DailyRate              Department  \
0      41      Travel_Rarely       1102                   Sales   
1      49  Travel_Frequently        279  Research & Development   
2      37      Travel_Rarely       1373  Research & Development   
3      33  Travel_Frequently       1392  Research & Development   
4      27      Travel_Rarely        591  Research & Development   
...   ...                ...        ...                     ...   
1465   36  Travel_Frequently        884  Research & Development   
1466   39      Travel_Rarely        613  Research & Development   
1467   27      Travel_Rarely        155  Research & Development   
1468   49  Travel_Frequently       1023                   Sales   
1469   34      Travel_Rarely        628  Research & Development   

      DistanceFromHome  Education EducationField  EnvironmentSatisfaction  \
0                    1          2  Life Sciences                        2   
1                    8          1  Life Sciences                        3   
2                    2          2          Other                        4   
3                    3          4  Life Sciences                        4   
4                    2          1        Medical                        1   
...                ...        ...            ...                      ...   
1465                23          2        Medical                        3   
1466                 6          1        Medical                        4   
1467                 4          3  Life Sciences                        2   
1468                 2          3        Medical                        4   
1469                 8          3        Medical                        2   

      Gender  HourlyRate  ...  PerformanceRating  RelationshipSatisfaction  \
0     Female          94  ...                  3                         1   
1       Male          61  ...                  4                         4   
2       Male          92  ...                  3                         2   
3     Female          56  ...                  3                         3   
4       Male          40  ...                  3                         4   
...      ...         ...  ...                ...                       ...   
1465    Male          41  ...                  3                         3   
1466    Male          42  ...                  3                         1   
1467    Male          87  ...                  4                         2   
1468    Male          63  ...                  3                         4   
1469    Male          82  ...                  3                         1   

     StockOptionLevel  TotalWorkingYears TrainingTimesLastYear  \
0                   0                  8                     0   
1                   1                 10                     3   
2                   0                  7                     3   
3                   0                  8                     3   
4                   1                  6                     3   
...               ...                ...                   ...   
1465                1                 17                     3   
1466                1                  9                     5   
1467                1                  6                     0   
1468                0                 17                     3   
1469                0                  6                     3   

      WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
0                   1               6                   4   
1                   3              10                   7   
2                   3               0                   0   
3                   3               8                   7   
4                   3               2                   2   
...               ...             ...                 ...   
1465                3               5                   2   
1466                3               7                   7 

In [9]:
print(y)

['Yes' 'No' 'Yes' ... 'No' 'No' 'No']


In [10]:
# get all features and categorical features
features = list(x.columns)
categorical_features = [] # store the indices of the columns
for i, feature in enumerate(features):
    if isinstance(x.iloc[0][feature], str):
        categorical_features.append(i)

In [11]:
print(len(features))
print(features)

30
['Age', 'BusinessTravel', 'DailyRate', 'Department', 'DistanceFromHome', 'Education', 'EducationField', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']


In [12]:
print(len(categorical_features))
print(categorical_features)

7
[1, 3, 6, 8, 12, 14, 18]


In [13]:
# convert the dataframe into ndarray (matrix of features)
x = x.iloc[:, :].values
print(type(x))
print(x.shape)
print(x)

<class 'numpy.ndarray'>
(1470, 30)
[[41 'Travel_Rarely' 1102 ... 4 0 5]
 [49 'Travel_Frequently' 279 ... 7 1 7]
 [37 'Travel_Rarely' 1373 ... 0 0 0]
 ...
 [27 'Travel_Rarely' 155 ... 2 0 3]
 [49 'Travel_Frequently' 1023 ... 6 0 8]
 [34 'Travel_Rarely' 628 ... 3 1 2]]


# Encoding Categorical Data

In [14]:
# encode matrix of features
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

column_transformer = ColumnTransformer(
    transformers = [('encoder', OneHotEncoder(), categorical_features)],
    remainder = 'passthrough'
)

x = column_transformer.fit_transform(x)

In [16]:
print(x.shape)
print(x[0])
print(x)

(1470, 51)
[0.0 0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 1.0 41 1102 1 2 2 94 3 2 4 5993 19479
 8 11 3 1 0 8 0 1 6 4 0 5]
[[0.0 0.0 1.0 ... 4 0 5]
 [0.0 1.0 0.0 ... 7 1 7]
 [0.0 0.0 1.0 ... 0 0 0]
 ...
 [0.0 0.0 1.0 ... 2 0 3]
 [0.0 1.0 0.0 ... 6 0 8]
 [0.0 0.0 1.0 ... 3 1 2]]


In [28]:
# encode target variable
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

y = label_encoder.fit_transform(y)

In [30]:
print(y.shape)
print(y[0])
print(set(y)) # distinct output classes
print(y)

(1470,)
1
{0, 1}
[1 0 1 ... 0 0 0]


# Split the dataset into training & test set

In [31]:
# split dataset into training & test set
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)

In [32]:
print(type(x_train))
print(x_train.shape)
print(x_train)

<class 'numpy.ndarray'>
(1029, 51)
[[0.0 0.0 1.0 ... 4 1 3]
 [0.0 0.0 1.0 ... 2 0 1]
 [0.0 0.0 1.0 ... 0 1 0]
 ...
 [0.0 1.0 0.0 ... 0 0 0]
 [0.0 0.0 1.0 ... 3 0 3]
 [0.0 0.0 1.0 ... 0 0 0]]


In [33]:
print(type(y_train))
print(y_train.shape)
print(y_train)

<class 'numpy.ndarray'>
(1029,)
[0 0 1 ... 1 0 0]


In [34]:
print(type(x_test))
print(x_test.shape)
print(x_test)

<class 'numpy.ndarray'>
(441, 51)
[[0.0 0.0 1.0 ... 4 1 3]
 [0.0 0.0 1.0 ... 2 1 3]
 [0.0 0.0 1.0 ... 0 0 0]
 ...
 [0.0 0.0 1.0 ... 2 2 2]
 [0.0 0.0 1.0 ... 4 0 4]
 [0.0 0.0 1.0 ... 0 0 0]]


In [35]:
print(type(y_test))
print(y_test.shape)
print(y_test)

<class 'numpy.ndarray'>
(441,)
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 1 1 0 0 0 0 0 1 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1
 0 1 0 1 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1
 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1]


# Training the Random Forest Classifier

- https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

- Below we are training a random forest classifier, with no restriction on the `max_depth`, and it used `100` decision trees (default), and used `gini` as the splitting criterion.

In [37]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier()

# train the model
clf.fit(x_train, y_train)

RandomForestClassifier()

# Predicting Test set results

In [38]:
y_pred = clf.predict(x_test)
print(y_pred)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


# Computing the Confusion Matrix, Classification Report & Accuracy Score

In [39]:
# confusion matrix
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

confusion_matrix(y_test, y_pred)

array([[377,   3],
       [ 56,   5]], dtype=int64)

In [40]:
# accuracy score
accuracy_score(y_test, y_pred)

0.8662131519274376

In [42]:
# classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.99      0.93       380
           1       0.62      0.08      0.14        61

    accuracy                           0.87       441
   macro avg       0.75      0.54      0.54       441
weighted avg       0.84      0.87      0.82       441



> **NOTE:** In order to visualize a decision tree from the random forest, follow this link: https://towardsdatascience.com/4-ways-to-visualize-individual-decision-trees-in-a-random-forest-7a9beda1d1b7

# Training a Decision Tree model, to compare results

In [43]:
from sklearn.tree import DecisionTreeClassifier

clf_decision_tree = DecisionTreeClassifier()

# train the decision tree model
clf_decision_tree.fit(x_train, y_train)

# predict test set results
y_pred_decision_tree = clf_decision_tree.predict(x_test)

# view confusion matrix
print(confusion_matrix(y_test, y_pred_decision_tree))

# view accuracy score
print(accuracy_score(y_test, y_pred_decision_tree))

# view classification report
print(classification_report(y_test, y_pred_decision_tree))

[[324  56]
 [ 39  22]]
0.7845804988662132
              precision    recall  f1-score   support

           0       0.89      0.85      0.87       380
           1       0.28      0.36      0.32        61

    accuracy                           0.78       441
   macro avg       0.59      0.61      0.59       441
weighted avg       0.81      0.78      0.80       441

