# Dataset Description

- Dataset of a bank, which collected customer information.

- Tenure: Number of years they are with the bank

- NumOfProducts: Number of products of the bank a customer is using

- Exited: Dependent Variable
    - Yes or No, if the customer stayed in the bank(0), or exited the bank (1)

- Understand the correlation between the features and whether or not the customer has stayed with the bank.

- For new customers, the model will predict if the customer will leave the bank. So that, the bank will take some preventive measure to retain the customers.

- We will predict the probability that the customer will leave the bank (`output = 1`)

# Importing the libraries

- numpy
- pandas
- tensorflow

TensorFlow is preinstalled in Google Colab. We still need to import it.

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
# check the version of tensorflow
tf.__version__

'2.9.2'

# 1. Data Preprocessing

## Importing the dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
# get matrix of features and dependent variable vector
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(type(X))
print(X.shape)
print(X)

<class 'numpy.ndarray'>
(10000, 10)
[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(type(y))
print(y.shape)
print(y)

<class 'numpy.ndarray'>
(10000,)
[1 0 1 ... 1 1 0]


## Encoding Categorical Data

- do label encoding for binary categories (gender)

- do one hot encoding for other categories (geography)

In [7]:
# Label Encoding 'Gender' column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [8]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [9]:
# One Hot Encoding for 'Geography' column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [
    ('encoder', OneHotEncoder(), [1])
], remainder = 'passthrough')

X = np.array(ct.fit_transform(X))

In [10]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


## Splitting dataset into training and test set

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [12]:
print(type(X_train))
print(X_train.shape)
print(X_train)

<class 'numpy.ndarray'>
(8000, 12)
[[0.0 0.0 1.0 ... 1 0 163830.64]
 [0.0 1.0 0.0 ... 1 1 57098.0]
 [1.0 0.0 0.0 ... 1 0 185630.76]
 ...
 [1.0 0.0 0.0 ... 1 0 181429.87]
 [0.0 0.0 1.0 ... 1 1 148750.16]
 [0.0 1.0 0.0 ... 1 0 118855.26]]


In [13]:
print(type(y_train))
print(y_train.shape)
print(y_train)

<class 'numpy.ndarray'>
(8000,)
[0 0 0 ... 0 0 1]


In [14]:
print(type(X_test))
print(X_test.shape)
print(X_test)

<class 'numpy.ndarray'>
(2000, 12)
[[0.0 1.0 0.0 ... 1 1 192852.67]
 [1.0 0.0 0.0 ... 1 0 128702.1]
 [0.0 0.0 1.0 ... 1 1 75732.25]
 ...
 [0.0 0.0 1.0 ... 1 0 141533.19]
 [0.0 1.0 0.0 ... 1 1 11276.48]
 [0.0 1.0 0.0 ... 1 0 192950.6]]


In [15]:
print(type(y_test))
print(y_test.shape)
print(y_test)

<class 'numpy.ndarray'>
(2000,)
[0 1 0 ... 0 0 0]


## Feature Scaling

- Feature Scaling is very important for Deep Learning.
- Feature Scaling will be applied to all features, including dummy variables, for both training set and test set.

In [16]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
print(X_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


In [18]:
print(X_test)

[[-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
   1.61085707]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   0.49587037]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   0.71888467]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -1.54507805]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   1.61255917]]


# Building the ANN

## Initializing the ANN

1. Create a variable, which itself is the ANN. It is an object of the `Sequential` class, which is a sequence of layers, the ANN itself.
    - `Sequential` class is Available in `tensorflow.keras.models` module.

In [19]:
from tensorflow.keras.models import Sequential
ann = Sequential()

## Adding the input layer and the first hidden layer

- Input layer is taken care of, based on number of input features.

- We need to add each layer one by one for each hidden layer.

- We make use of `Dense` class 
    - A fully connected layer is created using this class.

- The layer itself is an object of the `Dense` class available in `tensorflow.keras.layers` module

- `Dense(units = number_of_neurons, activation = activation_func)`

- How to choose the number of neurons? There is no rule of thumb. It is just based on **experimentation**.

- In hidden layers, its good to use `relu` activation function.

In [20]:
from tensorflow.keras.layers import Dense

hidden_layer_1 = Dense(units = 6, activation = 'relu')

ann.add(hidden_layer_1)

## Adding the second hidden layer

In [21]:
hidden_layer_2 = Dense(units = 6, activation = 'relu')

ann.add(hidden_layer_2)

## Adding the output layer

- Output layer is still a dense layer.

- But, the number of neurons (units) is the number of dimensions in the output (the number of classes in the classification).

- For binary classification, a single output neuron is enough.

- For 3 classes, you need 3 neurons in the output layer.

- For output layer, its better to use the sigmoid activation function.
    - Allows to get predictions, and probabilities for binary output.

In [22]:
output_layer = Dense(units = 1, activation = 'sigmoid')

ann.add(output_layer)

# Training the ANN

## Compiling the ANN

- With optimizer, loss function and a metric (accuracy in this case, for classification)

- Call the `compile` method on the model variable.

- `compile(optimizer, loss, metrics)`

- Best optimizers: the ones which perform Stochastic Gradient Descent
    - Adam's algorithm is a good one here.

- For binary classification, its good to use `binary_crossentropy` loss function.

- For non-activation classification, use `categorical_crossentropy` loss function.
    - Use `softmax` as the activation in the output, not `sigmoid`.

In [23]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

## Training the ANN on the Training Set

- On the ann object, use `fit` method and train it for a number of epochs.
- Batch learning is more efficient in ANN. (usually, `batch_size` is chosen as 32). It is actually a hyper parameter, which can be tuned.
- An ANN should be trained for a certain number of epochs, to improve its accuracy.
- `fit(X_train, y_train, batch_size = ..., epochs = ...)`

In [24]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.5831 - accuracy: 0.7539
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4727 - accuracy: 0.7985
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4406 - accuracy: 0.8089
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4294 - accuracy: 0.8119
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4233 - accuracy: 0.8189
Epoch 6/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4192 - accuracy: 0.8225
Epoch 7/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4160 - accuracy: 0.8259
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4137 - accuracy: 0.8279
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4121 - accuracy: 0.8304
Epoch 10/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4111 - accura

# Making Predictions & Evaluating the model

## Predicting the result of a single observation

- `predict` method expects a 2D array as an input.

- Categorical variables like geography, gender need to be encoded (values of dummy variables as per matrix of features).
    - By looking at values during encoding, `France` is encoded as `100`
    - `Male` was encoded as `1`.

- At the end, scale the observation with the same scaler as the training.

- Since the activation in our output layer is sigmoid function, we get probabilities.

In [27]:
observation = sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])

ann.predict(observation)

1/1 [==============================] - 1s 608ms/step


array([[0.01568859]], dtype=float32)

In [28]:
threshold = 0.5

ann.predict(observation) > threshold

1/1 [==============================] - 0s 36ms/step


array([[False]])

## Predicting the test set results

In [37]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > threshold).ravel() # convert y_pred into 1D array

63/63 [==============================] - 0s 3ms/step


In [38]:
print(y_pred)

[False False False ... False False False]


In [39]:
# compare actual and predicted results
results = pd.DataFrame({
    'Actual': y_test,
    'Predicted': y_pred
})
print(results)

      Actual  Predicted
0          0      False
1          1      False
2          0      False
3          0      False
4          0      False
...      ...        ...
1995       0      False
1996       0      False
1997       0      False
1998       0      False
1999       0      False

[2000 rows x 2 columns]


## Making the Confustion Matrix

In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)

cm

array([[1519,   76],
       [ 201,  204]])

In [41]:
accuracy_score(y_test, y_pred)

0.8615